# Task 13: Data manipulation with Pandas (indexing, selection, grouping)

In [112]:
import pandas as pd

#### Load a DataFrame from a CSV file. Display the first and last five rows of the DataFrame.

In [113]:
file_path = 'laptop_price_data.csv'
df = pd.read_csv(file_path)
df

,Company,TypeName,Ram,Weight,Price,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os
0,Apple,Ultrabook,8,1.37,11.175755,0,1,226.983005,Intel Core i5,0,128,Intel,Mac
1,Apple,Ultrabook,8,1.34,10.776777,0,0,127.677940,Intel Core i5,0,0,Intel,Mac
2,HP,Notebook,8,1.86,10.329931,0,0,141.211998,Intel Core i5,0,256,Intel,Others
3,Apple,Ultrabook,16,1.83,11.814476,0,1,220.534624,Intel Core i7,0,512,AMD,Mac
4,Apple,Ultrabook,8,1.37,11.473101,0,1,226.983005,Intel Core i5,0,256,Intel,Mac
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1268,Asus,Notebook,4,2.20,10.555257,0,0,100.454670,Intel Core i7,500,0,Nvidia,Windows
1269,Lenovo,2 in 1 Convertible,4,1.80,10.433899,1,1,157.350512,Intel Core i7,0,128,Intel,Windows
1270,Lenovo,2 in 1 Convertible,16,1.30,11.288115,1,1,276.053530,Intel Core i7,0,512,Intel,Windows
1271,Lenovo,Notebook,2,1.50,9.409283,0,0,111.935204,Other Intel Processor,0,0,Intel,Windows
1272,HP,Notebook,6,2.19,10.614129,0,0,100.454670,Intel Core i7,1000,0,AMD,Windows

In [114]:
df.head()

,Company,TypeName,Ram,Weight,Price,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os
0,Apple,Ultrabook,8,1.37,11.175755,0,1,226.983005,Intel Core i5,0,128,Intel,Mac
1,Apple,Ultrabook,8,1.34,10.776777,0,0,127.677940,Intel Core i5,0,0,Intel,Mac
2,HP,Notebook,8,1.86,10.329931,0,0,141.211998,Intel Core i5,0,256,Intel,Others
3,Apple,Ultrabook,16,1.83,11.814476,0,1,220.534624,Intel Core i7,0,512,AMD,Mac
4,Apple,Ultrabook,8,1.37,11.473101,0,1,226.983005,Intel Core i5,0,256,Intel,Mac

In [115]:
df.tail()

,Company,TypeName,Ram,Weight,Price,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os
1268,Asus,Notebook,4,2.20,10.555257,0,0,100.454670,Intel Core i7,500,0,Nvidia,Windows
1269,Lenovo,2 in 1 Convertible,4,1.80,10.433899,1,1,157.350512,Intel Core i7,0,128,Intel,Windows
1270,Lenovo,2 in 1 Convertible,16,1.30,11.288115,1,1,276.053530,Intel Core i7,0,512,Intel,Windows
1271,Lenovo,Notebook,2,1.50,9.409283,0,0,111.935204,Other Intel Processor,0,0,Intel,Windows
1272,HP,Notebook,6,2.19,10.614129,0,0,100.454670,Intel Core i7,1000,0,AMD,Windows

#### Set a specific column as the index of the DataFrame.

In [116]:
df.set_index('Company', inplace=True)

In [117]:
df.head()

,TypeName,Ram,Weight,Price,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os
Company,,,,,,,,,,,,
Apple,Ultrabook,8,1.37,11.175755,0,1,226.983005,Intel Core i5,0,128,Intel,Mac
Apple,Ultrabook,8,1.34,10.776777,0,0,127.677940,Intel Core i5,0,0,Intel,Mac
HP,Notebook,8,1.86,10.329931,0,0,141.211998,Intel Core i5,0,256,Intel,Others
Apple,Ultrabook,16,1.83,11.814476,0,1,220.534624,Intel Core i7,0,512,AMD,Mac
Apple,Ultrabook,8,1.37,11.473101,0,1,226.983005,Intel Core i5,0,256,Intel,Mac

In [118]:
#### Select a specific column and display its values.

In [119]:
ram_values = df['Ram']
ram_values

Company
Apple      8
Apple      8
HP         8
Apple     16
Apple      8
          ..
Asus       4
Lenovo     4
Lenovo    16
Lenovo     2
HP         6
Name: Ram, Length: 1273, dtype: int64

#### Select multiple columns and display the resulting DataFrame.

In [120]:
selected_columns_df = df[['TypeName', 'Price', 'Os']]
selected_columns_df

                   TypeName      Price       Os
Company
Apple             Ultrabook  11.175755      Mac
Apple             Ultrabook  10.776777      Mac
HP                 Notebook  10.329931   Others
Apple             Ultrabook  11.814476      Mac
Apple             Ultrabook  11.473101      Mac
...                     ...        ...      ...
Asus               Notebook  10.555257  Windows
Lenovo   2 in 1 Convertible  10.433899  Windows
Lenovo   2 in 1 Convertible  11.288115  Windows
Lenovo             Notebook   9.409283  Windows
HP                 Notebook  10.614129  Windows

[1273 rows x 3 columns]

#### Select a subset of rows using the .loc method.

In [121]:
subset_loc = df.loc['Apple']
subset_loc

,TypeName,Ram,Weight,Price,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os
Company,,,,,,,,,,,,
Apple,Ultrabook,8,1.37,11.175755,0,1,226.983005,Intel Core i5,0,128,Intel,Mac
Apple,Ultrabook,8,1.34,10.776777,0,0,127.677940,Intel Core i5,0,0,Intel,Mac
Apple,Ultrabook,16,1.83,11.814476,0,1,220.534624,Intel Core i7,0,512,AMD,Mac
Apple,Ultrabook,8,1.37,11.473101,0,1,226.983005,Intel Core i5,0,256,Intel,Mac
Apple,Ultrabook,16,2.04,11.644108,0,1,220.534624,Intel Core i7,0,0,Intel,Mac
Apple,Ultrabook,8,1.34,11.030615,0,0,127.677940,Intel Core i5,0,0,Intel,Mac
Apple,Ultrabook,16,1.83,11.775302,0,1,220.534624,Intel Core i7,0,256,AMD,Mac
Apple,Ultrabook,8,0.92,11.116331,0,1,226.415547,Other Intel Processor,0,256,Intel,Mac
Apple,Ultrabook,8,1.37,11.301072,0,1,226.983005,Intel Core i5,0,256,Intel,Mac
Apple,Ultrabook,16,1.83,11.933438,0,1,220.534624,Intel Core i7,0,512,AMD,Mac
Apple,Ultrabook,8,1.35,10.977717,0,0,127.677940,Intel Core i5,0,0,Intel,Mac
Apple,Ultrabook,8,1.35,10.881314,0,0,127.677940,Intel Core i5,0,0,Intel,Mac
Apple,Ultrabook,8,1.37,11.233269,0,1,226.983005,Intel Core i5,0,256,Intel,Mac
Apple,Ultrabook,8,0.92,11.295426,0,1,226.415547,Intel Core i5,0,512,Intel,Mac
Apple,Ultrabook,8,1.37,11.596266,0,1,226.983005,Intel Core i5,0,512,Intel,Mac
Apple,Ultrabook,8,1.37,11.555699,0,1,226.983005,Intel Core i5,0,512,Intel,Mac
Apple,Ultrabook,8,0.92,11.036037,0,1,226.415547,Other Intel Processor,0,0,Intel,Mac
Apple,Ultrabook,8,0.92,11.145681,0,1,226.415547,Other Intel Processor,0,0,Intel,Mac
Apple,Ultrabook,8,0.92,11.034319,0,1,226.415547,Other Intel Processor,0,0,Intel,Mac
Apple,Ultrabook,8,0.92,11.129395,0,1,226.415547,Other Intel Processor,0,0,Intel,Mac
Apple,Ultrabook,4,1.08,10.841452,0,0,135.094211,Intel Core i5,0,0,Intel,Mac

#### Select a subset of rows and columns using the .iloc method.

In [122]:
subset_iloc = df.iloc[0:5, 0:3]
subset_iloc

          TypeName  Ram  Weight
Company
Apple    Ultrabook    8    1.37
Apple    Ultrabook    8    1.34
HP        Notebook    8    1.86
Apple    Ultrabook   16    1.83
Apple    Ultrabook    8    1.37

#### Filter rows based on a condition.

In [123]:
filtered_rows = df[df['Price'] > 11]
filtered_rows

,TypeName,Ram,Weight,Price,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os
Company,,,,,,,,,,,,
Apple,Ultrabook,8,1.37,11.175755,0,1,226.983005,Intel Core i5,0,128,Intel,Mac
Apple,Ultrabook,16,1.83,11.814476,0,1,220.534624,Intel Core i7,0,512,AMD,Mac
Apple,Ultrabook,8,1.37,11.473101,0,1,226.983005,Intel Core i5,0,256,Intel,Mac
Apple,Ultrabook,16,2.04,11.644108,0,1,220.534624,Intel Core i7,0,0,Intel,Mac
Apple,Ultrabook,8,1.34,11.030615,0,0,127.677940,Intel Core i5,0,0,Intel,Mac
...,...,...,...,...,...,...,...,...,...,...,...,...
Asus,Gaming,16,2.34,11.727036,0,1,141.211998,Intel Core i7,1000,256,Nvidia,Windows
Dell,2 in 1 Convertible,8,1.24,11.478299,1,0,276.053530,Intel Core i5,0,256,Intel,Windows
Asus,Gaming,16,4.00,11.525170,0,1,127.335675,Intel Core i7,1000,128,Nvidia,Windows
MSI,Gaming,8,2.40,11.089517,0,0,141.211998,Intel Core i7,1000,128,Nvidia,Windows
Lenovo,2 in 1 Convertible,16,1.30,11.288115,1,1,276.053530,Intel Core i7,0,512,Intel,Windows

#### Group the DataFrame by a specific column and calculate the mean of each group.

In [124]:
mean_by_company = df.groupby('Company').mean(numeric_only=True)
mean_by_company

,Ram,Weight,Price,TouchScreen,Ips,Ppi,HDD,SSD
Company,,,,,,,,
Acer,6.019802,2.162277,10.301821,0.099010,0.346535,126.638825,440.594059,89.346535
Apple,9.333333,1.320476,11.274645,0.000000,0.761905,202.301704,0.000000,188.952381
Asus,9.801325,2.234377,10.797073,0.092715,0.185430,137.583440,603.496689,183.364238
Chuwi,4.666667,1.726667,9.683992,0.000000,0.333333,183.254144,0.000000,0.000000
Dell,9.230241,2.144574,10.924479,0.219931,0.154639,152.856737,475.945017,194.804124
Fujitsu,6.666667,2.233333,10.563592,0.000000,0.000000,100.454670,333.333333,170.666667
Google,10.666667,1.100000,11.374981,1.000000,0.000000,234.507400,0.000000,298.666667
HP,6.962687,1.913806,10.805129,0.100746,0.212687,143.847152,350.746269,168.507463
Huawei,8.000000,1.050000,11.235397,0.000000,1.000000,199.692071,0.000000,384.000000
LG,10.666667,1.050000,11.621737,0.666667,1.000000,146.591503,0.000000,512.000000
Lenovo,8.055363,2.007889,10.779085,0.169550,0.460208,149.032210,342.560554,204.276817
MSI,13.037037,2.660556,11.383340,0.000000,0.129630,139.446724,981.481481,232.296296
Mediacom,3.714286,1.337143,9.645522,0.142857,0.714286,164.992422,4.571429,18.285714
Microsoft,8.000000,1.251333,11.305010,1.000000,0.000000,200.842560,0.000000,256.000000
Razer,19.428571,2.195714,11.940528,0.571429,0.142857,240.903504,0.000000,578.285714
Samsung,11.500000,1.336250,11.173723,0.250000,0.000000,151.723000,125.000000,208.000000
Toshiba,8.666667,1.640208,11.044669,0.104167,0.375000,140.870288,93.750000,226.666667
Vero,3.500000,1.330000,9.351166,0.000000,0.250000,148.067086,0.000000,0.000000
Xiaomi,10.000000,1.620000,10.995970,0.000000,1.000000,153.422058,0.000000,256.000000

#### Group the DataFrame by multiple columns and calculate the sum of each group.

In [125]:
sum_by_company_type = df.groupby(['Company', 'TypeName']).sum(numeric_only=True)
sum_by_company_type

                               Ram   Weight        Price  TouchScreen  Ips  \
Company   TypeName
Acer      2 in 1 Convertible    52   11.250    83.461799            8    8
          Gaming                96   25.100    89.270163            0    5
          Netbook               18    6.700    48.272768            0    2
          Notebook             410  169.220   776.426111            2   16
          Ultrabook             32    6.120    43.053072            0    4
Apple     Ultrabook            196   27.730   236.767551            0   16
Asus      2 in 1 Convertible   104   20.130   139.622604           12    1
          Gaming               808  161.181   613.250157            1   20
          Netbook               12    4.480    38.152036            0    0
          Notebook             356  127.560   638.685400            0    3
          Ultrabook            200   24.040   200.647788            1    4
Chuwi     Notebook              14    5.180    29.051975            0    1
Dell      2 in 1 Convertible   280   53.381   327.901188           30    8
          Gaming               632  132.390   456.771355            1   16
          Netbook                8    2.890    20.250138            0    0
          Notebook            1210  342.830  1695.575342           12    6
          Ultrabook            436   67.710   550.321573           19   12
          Workstation          120   24.870   128.203777            2    3
Fujitsu   Notebook              20    6.700    31.690775            0    0
Google    Ultrabook             32    3.300    34.124942            3    0
HP        2 in 1 Convertible   152   27.150   212.437818           19    6
          Gaming               132   37.510   134.536402            0   10
          Netbook               42    9.550    76.013591            0    0
          Notebook            1132  350.390  1904.559325            3   25
          Ultrabook            280   51.290   404.986792            5   10
          Workstation          128   37.010   163.240642            0    6
Huawei    Ultrabook             16    2.100    22.470794            0    2
LG        Ultrabook             32    3.150    34.865212            2    3
Lenovo    2 in 1 Convertible   396   65.010   492.767033           43   36
          Gaming               396   92.020   355.113581            1   30
          Netbook               28    5.540    41.369177            2    2
          Notebook            1142  365.380  1824.487314            1   39
          Ultrabook            310   42.680   354.524695            2   24
          Workstation           56    9.650    46.893740            0    2
MSI       Gaming               704  143.670   614.700345            0    7
Mediacom  2 in 1 Convertible     4    1.160     9.676005            1    1
          Notebook              22    8.200    57.842652            0    4
Microsoft Ultrabook             48    7.508    67.830057            6    0
Razer     Gaming               112   12.830    61.201242            2    0
          Ultrabook             24    2.540    22.382451            2    1
Samsung   2 in 1 Convertible    16    1.710    11.470547            1    0
          Netbook                4    1.150     9.570272            0    0
          Notebook              16    2.500    11.413356            0    0
          Ultrabook             56    5.330    56.935612            1    0
Toshiba   Notebook             260   63.940   393.258613            1   16
          Ultrabook            156   14.790   136.885481            4    2
Vero      Notebook              14    5.320    37.404663            0    1
Xiaomi    Notebook              24    3.900    22.284557            0    2
          Ultrabook             16    2.580    21.699324            0    2

                                       Ppi    HDD    SSD
Company   TypeName
Acer      2 in 1 Convertible   1279.973197      0   1280
          Gaming               1088.067014   6000   1280
          Netbook               675.471056      0    160
          Notebook             9109.326358  38500   5280
          Ultrabook             637.683654      0   1024
Apple     Ultrabook            4248.335778      0   3968
Asus      2 in 1 Convertible   2116.116822   8000   2816
          Gaming               7139.776574  48000  12136
          Netbook               540.376845      0      0
          Notebook             8056.501078  34128   5824
          Ultrabook            2922.328151   1000   6912
Chuwi     Notebook              549.762432      0      0
Dell      2 in 1 Convertible   4934.606813   7000   7296
          Gaming               6782.257180  33000  10320
          Netbook               270.188422      0    128
          Notebook            21050.886616  92500  21968
          Ultrabook            9621.491753   2500  14672
          Workstation          1821.879652   3500   2304
Fujitsu   Notebook              301.364010   1000    512
Google    Ultrabook             703.522200      0    896
HP        2 in 1 Convertible   3651.871059    500   5224
          Gaming               1569.657065  12000   1408
          Netbook              1049.620999      0   1664
          Notebook            23810.421596  78500  23048
          Ultrabook            6583.102203   1000  10992
          Workstation          1886.363743   2000   2824
Huawei    Ultrabook             399.384141      0    768
LG        Ultrabook             439.774508      0   1536
Lenovo    2 in 1 Convertible   8438.414097      0  15312
          Gaming               4463.278645  24000   7296
          Netbook               581.515207      0    784
          Notebook            23352.014728  75000  22276
          Ultrabook            5387.814095      0  10832
          Workstation           847.271988      0   2536
MSI       Gaming               7530.123080  53000  12544
Mediacom  2 in 1 Convertible    189.905791      0     32
          Notebook              965.041163     32     96
Microsoft Ultrabook            1205.055360      0   1536
Razer     Gaming                981.394235      0   3280
          Ultrabook             704.930294      0    768
Samsung   2 in 1 Convertible    146.860478      0    256
          Netbook               135.094211      0      0
          Notebook              141.211998   1000    128
          Ultrabook             790.617310      0   1280
Toshiba   Notebook             4889.935261   4500   6144
          Ultrabook            1871.838552      0   4736
Vero      Notebook              592.268346      0      0
Xiaomi    Notebook              282.423996      0    512
          Ultrabook             331.264236      0    512

#### Use the agg method to apply multiple aggregation functions to grouped data.

In [126]:
agg_functions = df.groupby('Company').agg({'Price': ['mean', 'max'], 'Ram': ['mean', 'min']})
agg_functions

               Price                   Ram
                mean        max       mean min
Company
Acer       10.301821  11.838443   6.019802   2
Apple      11.274645  11.933438   9.333333   4
Asus       10.797073  12.263341   9.801325   2
Chuwi       9.683992  10.082584   4.666667   4
Dell       10.924479  12.180616   9.230241   2
Fujitsu    10.563592  10.658922   6.666667   4
Google     11.374981  11.671319  10.666667   8
HP         10.805129  12.362418   6.962687   2
Huawei     11.235397  11.288115   8.000000   8
LG         11.621737  11.715791  10.666667   8
Lenovo     10.779085  12.472347   8.055363   2
MSI        11.383340  11.912579  13.037037   8
Mediacom    9.645522   9.939140   3.714286   2
Microsoft  11.305010  11.834588   8.000000   4
Razer      11.940528  12.691441  19.428571   8
Samsung    11.173723  11.497961  11.500000   4
Toshiba    11.044669  11.912579   8.666667   4
Vero        9.351166   9.536243   3.500000   2
Xiaomi     10.995970  11.219753  10.000000   8

#### Calculate the size of each group.

In [127]:
size_by_company = df.groupby('Company').size()
size_by_company

Company
Acer         101
Apple         21
Asus         151
Chuwi          3
Dell         291
Fujitsu        3
Google         3
HP           268
Huawei         2
LG             3
Lenovo       289
MSI           54
Mediacom       7
Microsoft      6
Razer          7
Samsung        8
Toshiba       48
Vero           4
Xiaomi         4
dtype: int64

#### Select rows based on multiple conditions.

In [128]:
multiple_conditions = df[(df['Ram'] > 8) & (df['TouchScreen'] == 1)]
multiple_conditions

,TypeName,Ram,Weight,Price,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os
Company,,,,,,,,,,,,
Dell,Ultrabook,16,1.20,11.508720,1,0,276.053530,Intel Core i7,0,512,Intel,Windows
Dell,2 in 1 Convertible,12,2.77,10.882316,1,0,127.335675,Intel Core i5,1000,0,Nvidia,Windows
Lenovo,2 in 1 Convertible,16,1.40,11.497961,1,1,316.965060,Intel Core i7,0,512,Intel,Windows
Dell,Notebook,16,2.77,11.320926,1,0,127.335675,Intel Core i7,0,512,Nvidia,Windows
Dell,Notebook,16,2.06,11.757534,1,0,282.423996,Intel Core i7,0,512,Nvidia,Windows
Lenovo,2 in 1 Convertible,16,1.42,11.921471,1,0,209.800683,Intel Core i7,0,1000,Intel,Windows
Razer,Gaming,32,3.49,12.691441,1,0,254.671349,Intel Core i7,0,1000,Nvidia,Windows
Dell,2 in 1 Convertible,16,1.62,11.129395,1,0,165.632118,Intel Core i7,0,512,Intel,Windows
Dell,Notebook,16,2.30,10.731342,1,0,141.211998,Intel Core i7,1000,0,AMD,Windows
Lenovo,2 in 1 Convertible,16,1.36,11.799207,1,0,209.800683,Intel Core i7,0,512,Intel,Windows
Acer,Notebook,12,2.15,10.466285,1,1,141.211998,Intel Core i7,1000,0,Intel,Windows
HP,2 in 1 Convertible,16,1.28,11.563885,1,0,165.632118,Intel Core i7,0,256,Intel,Windows
Dell,Ultrabook,16,1.21,11.799207,1,1,331.264236,Intel Core i7,0,1000,Intel,Windows
HP,2 in 1 Convertible,16,1.29,11.778996,1,1,331.264236,Intel Core i7,0,1000,Intel,Windows
Dell,Notebook,32,2.06,11.853716,1,0,282.423996,Intel Core i7,0,1000,Nvidia,Windows
Lenovo,2 in 1 Convertible,16,1.40,11.624777,1,1,316.965060,Intel Core i7,0,512,Intel,Windows
Dell,Notebook,16,2.06,11.590080,1,0,282.423996,Intel Core i7,0,512,Nvidia,Windows
Asus,2 in 1 Convertible,12,2.26,10.977717,1,0,141.211998,Intel Core i7,2000,512,Nvidia,Windows
Asus,Ultrabook,16,1.10,11.442303,1,0,165.632118,Intel Core i7,0,512,Intel,Windows
Lenovo,2 in 1 Convertible,16,1.42,11.803201,1,0,209.800683,Intel Core i7,0,512,Intel,Windows
Lenovo,2 in 1 Convertible,16,2.00,11.524644,1,1,282.423996,Intel Core i7,0,512,Nvidia,Windows
Google,Ultrabook,16,1.10,11.671319,1,0,234.507400,Intel Core i7,0,512,Intel,Others
Microsoft,Ultrabook,16,1.25,11.834588,1,0,200.842560,Intel Core i7,0,512,Intel,Windows
Toshiba,Ultrabook,32,1.05,11.912579,1,0,165.632118,Intel Core i7,0,512,Intel,Windows
Asus,Gaming,24,4.33,11.121545,1,1,127.335675,Intel Core i7,1000,256,Nvidia,Windows
HP,Ultrabook,16,1.16,11.558809,1,1,276.053530,Other Intel Processor,0,512,Intel,Windows
Toshiba,Ultrabook,16,1.24,11.506577,1,0,157.350512,Intel Core i7,0,512,Intel,Windows
Lenovo,Notebook,12,2.20,10.387379,1,0,100.454670,Intel Core i7,1000,0,Intel,Windows
Dell,Notebook,16,2.06,11.758368,1,0,282.423996,Intel Core i7,0,1000,Nvidia,Windows
Lenovo,2 in 1 Convertible,16,1.38,11.442361,1,0,157.350512,Intel Core i7,0,512,Intel,Windows
Toshiba,Ultrabook,16,1.36,11.512991,1,0,165.632118,Intel Core i7,0,512,Intel,Windows
Dell,Gaming,16,2.72,10.977717,1,1,282.423996,Intel Core i7,1000,128,Nvidia,Windows
Samsung,2 in 1 Convertible,16,1.71,11.470547,1,0,146.860478,Intel Core i7,0,256,AMD,Windows
Asus,2 in 1 Convertible,12,2.30,10.707772,1,0,141.211998,Intel Core i7,2000,0,Nvidia,Windows
Razer,Ultrabook,16,1.29,11.470547,1,1,352.465147,Intel Core i7,0,512,Intel,Windows
Razer,Gaming,32,3.49,12.587883,1,0,254.671349,Intel Core i7,0,512,Nvidia,Windows
Dell,Ultrabook,16,1.29,11.689792,1,0,276.053530,Intel Core i7,0,512,Intel,Windows
HP,2 in 1 Convertible,16,1.42,11.219074,1,0,276.053530,Intel Core i7,0,256,Intel,Windows
Dell,2 in 1 Convertible,16,1.22,11.383485,1,0,165.632118,Intel Core i7,0,256,Intel,Windows
LG,Ultrabook,16,1.08,11.624777,1,1,141.211998,Intel Core i7,0,512,Intel,Windows
Lenovo,2 in 1 Convertible,16,1.30,11.470547,1,1,276.053530,Intel Core i7,0,1000,Intel,Windows
Dell,2 in 1 Convertible,16,1.22,11.524644,1,0,276.053530,Intel Core i7,0,512,Intel,Windows
Asus,2 in 1 Convertible,16,2.30,11.470547,1,0,282.423996,Intel Core i7,2000,512,Nvidia,Windows
Dell,2 in 1 Convertible,12,2.19,11.144911,1,1,141.211998,Intel Core i7,0,512,Intel,Windows
Dell,Ultrabook,16,1.20,11.696023,1,0,276.053530,Intel Core i7,0,1000,Intel,Windows
Dell,2 in 1 Convertible,12,1.60,11.144911,1,1,165.632118,Intel Core i7,0,256,Intel,Windows
Lenovo,2 in 1 Convertible,16,2.80,11.775314,1,1,209.800683,Intel Core i7,0,512,Intel,Windows
Dell,2 in 1 Convertible,16,2.09,11.047983,1,0,141.211998,Intel Core i7,0,512,Intel,Windows
Dell,2 in 1 Convertible,16,2.00,11.134075,1,0,141.211998,Intel Core i7,0,512,Intel,Windows
Dell,Ultrabook,16,1.20,11.869133,1,0,276.053530,Intel Core i7,0,512,Intel,Windows
Lenovo,Gaming,16,2.60,10.911904,1,1,141.211998,Intel Core i7,1000,128,Nvidia,Windows
Lenovo,Netbook,16,1.30,11.384092,1,1,176.232574,Intel Core i7,0,512,Intel,Windows
Dell,2 in 1 Convertible,16,2.77,11.470547,1,0,127.335675,Intel Core i7,0,512,Nvidia,Windows
Lenovo,2 in 1 Convertible,16,1.30,11.288115,1,1,276.053530,Intel Core i7,0,512,Intel,Windows

#### Use the query method to filter rows.

In [129]:
query_filtered = df.query('Price > 11')
query_filtered

,TypeName,Ram,Weight,Price,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os
Company,,,,,,,,,,,,
Apple,Ultrabook,8,1.37,11.175755,0,1,226.983005,Intel Core i5,0,128,Intel,Mac
Apple,Ultrabook,16,1.83,11.814476,0,1,220.534624,Intel Core i7,0,512,AMD,Mac
Apple,Ultrabook,8,1.37,11.473101,0,1,226.983005,Intel Core i5,0,256,Intel,Mac
Apple,Ultrabook,16,2.04,11.644108,0,1,220.534624,Intel Core i7,0,0,Intel,Mac
Apple,Ultrabook,8,1.34,11.030615,0,0,127.677940,Intel Core i5,0,0,Intel,Mac
...,...,...,...,...,...,...,...,...,...,...,...,...
Asus,Gaming,16,2.34,11.727036,0,1,141.211998,Intel Core i7,1000,256,Nvidia,Windows
Dell,2 in 1 Convertible,8,1.24,11.478299,1,0,276.053530,Intel Core i5,0,256,Intel,Windows
Asus,Gaming,16,4.00,11.525170,0,1,127.335675,Intel Core i7,1000,128,Nvidia,Windows
MSI,Gaming,8,2.40,11.089517,0,0,141.211998,Intel Core i7,1000,128,Nvidia,Windows
Lenovo,2 in 1 Convertible,16,1.30,11.288115,1,1,276.053530,Intel Core i7,0,512,Intel,Windows

#### Use isin to filter rows based on a list of values.

In [130]:
isin_filtered = df[df['Os'].isin(['Windows', 'Mac'])]
isin_filtered

,TypeName,Ram,Weight,Price,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os
Company,,,,,,,,,,,,
Apple,Ultrabook,8,1.37,11.175755,0,1,226.983005,Intel Core i5,0,128,Intel,Mac
Apple,Ultrabook,8,1.34,10.776777,0,0,127.677940,Intel Core i5,0,0,Intel,Mac
Apple,Ultrabook,16,1.83,11.814476,0,1,220.534624,Intel Core i7,0,512,AMD,Mac
Apple,Ultrabook,8,1.37,11.473101,0,1,226.983005,Intel Core i5,0,256,Intel,Mac
Acer,Notebook,4,2.10,9.967026,0,0,100.454670,AMD Processor,500,0,AMD,Windows
...,...,...,...,...,...,...,...,...,...,...,...,...
Asus,Notebook,4,2.20,10.555257,0,0,100.454670,Intel Core i7,500,0,Nvidia,Windows
Lenovo,2 in 1 Convertible,4,1.80,10.433899,1,1,157.350512,Intel Core i7,0,128,Intel,Windows
Lenovo,2 in 1 Convertible,16,1.30,11.288115,1,1,276.053530,Intel Core i7,0,512,Intel,Windows
Lenovo,Notebook,2,1.50,9.409283,0,0,111.935204,Other Intel Processor,0,0,Intel,Windows
HP,Notebook,6,2.19,10.614129,0,0,100.454670,Intel Core i7,1000,0,AMD,Windows

#### Select specific columns and rename them.

In [131]:
renamed_columns_df = df[['Ram', 'Weight', 'Price']].rename(columns={'Ram': 'Memory', 'Weight': 'Mass', 'Price': 'Cost'})
renamed_columns_df

         Memory  Mass       Cost
Company
Apple         8  1.37  11.175755
Apple         8  1.34  10.776777
HP            8  1.86  10.329931
Apple        16  1.83  11.814476
Apple         8  1.37  11.473101
...         ...   ...        ...
Asus          4  2.20  10.555257
Lenovo        4  1.80  10.433899
Lenovo       16  1.30  11.288115
Lenovo        2  1.50   9.409283
HP            6  2.19  10.614129

[1273 rows x 3 columns]